[package]
name = "distributed_swmr_registers"
version = "0.1.0"
authors = ["Oskar LundstrÃ¶m <21679735+osklunds@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.94", features = ["derive"] }
serde_json = "1.0.39"
