[package]
name = "local_starter"
version = "0.1.0"
authors = ["Oskar Lundstr√∂m <21679735+osklunds@users.noreply.github.com>"]
edition = "2018"

[dependencies]
commons = { path = "../commons" }
colored = "1.8.0"
lazy_static = "1.3.0"
clap = "2.33.0"